name: Deploy Docker to EC2

on:
  push:
    branches:
      - dev-v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Test SSH connection
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          port: 22
          script: |
            echo "Connected to $(hostname) as $(whoami)"

      # Docker Deployment
      - name: Deploy via Docker on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          port: 22
          script: |
            cd ${{ secrets.EC2_PATH }}/backend
            git pull origin dev-v2
            docker-compose down
            docker-compose build
            docker-compose up -d
            echo "Docker deployment completed!"
